baseurl = "https://stanyuzu.netlify.app/"
title = "NMB rankings"
author = "nvmea"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = true

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Stan Yuzu"
  faviconfile = "favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "Instagram"
    url = "https://instagram.com/h.yuzuha_0112"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/yuzuha_hongo"
    weight = 4
[[menu.primary]]
    name = "NMB tweet database"
    url = "https://nvmea.github.io/namba"
    weight = 5
    